from PySide6.QtWidgets import QCheckBox,QComboBox,QDialog,QDialogButtonBox,QDoubleSpinBox,QFormLayout,QLabel,QLineEdit,QMessageBox,QSpinBox
from app.core.config import settings


class CameraDialog(QDialog):
    def __init__(self,camera=None,parent=None):
        super().__init__(parent); self.setWindowTitle("Thêm camera" if camera is None else "Sửa camera"); self.resize(600,720); self.setMinimumWidth(520); form=QFormLayout(self); form.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
        self.code=QLineEdit(); self.name=QLineEdit(); self.position=QLineEdit(); self.url=QLineEdit(); self.url.setPlaceholderText("rtsp://user:password@host:port/path")
        for field in (self.code,self.name,self.position,self.url): field.setMinimumWidth(340)
        self.zone_type=QComboBox(); self.zone_type.addItem("-- Chọn loại khu vực --","LEGACY_UNSET"); self.zone_type.addItem("Khu vực ô tô","CAR_ZONE"); self.zone_type.addItem("Khu vực xe máy","MOTORCYCLE_ZONE")
        self.capacity=QSpinBox(); self.capacity.setRange(1,999)
        self.fps=QDoubleSpinBox(); self.fps.setRange(.1,60); self.preview_fps=QSpinBox(); self.preview_fps.setRange(1,15); self.preview_fps.setToolTip("Chỉ điều chỉnh độ mượt hình ảnh trên giao diện, không thay đổi tần suất nhận diện AI.")
        self.preview_warning=QLabel("⚠ FPS preview trên 10 có thể tăng tải giao diện."); self.preview_warning.setStyleSheet("color:#d97706;font-weight:600"); self.preview_warning.hide(); self.preview_fps.valueChanged.connect(lambda value:self.preview_warning.setVisible(value>10))
        self.conf=QDoubleSpinBox(); self.conf.setRange(.01,1); self.conf.setSingleStep(.05); self.imgsz=QComboBox(); [self.imgsz.addItem(str(v),v) for v in (640,768,960,1280)]; self.overlap=QDoubleSpinBox(); self.overlap.setRange(.01,1); self.overlap.setSingleStep(.05)
        self.roi=QCheckBox("Crop ROI polygon (+10%)"); self.debug_overlay=QCheckBox("Hiện AI debug overlay"); self.park=QSpinBox(); self.park.setRange(1,3600); self.exit=QSpinBox(); self.exit.setRange(1,600); self.grace=QSpinBox(); self.grace.setRange(1,600); self.miss_grace=QSpinBox(); self.miss_grace.setRange(1,60)
        self.rotation=QComboBox(); self.rotation.addItem("Không xoay",0); self.rotation.addItem("90° theo chiều kim đồng hồ",90); self.rotation.addItem("180°",180); self.rotation.addItem("90° ngược chiều kim đồng hồ",270); self.enabled=QCheckBox("Bật camera")
        for label,w in [("Mã camera*",self.code),("Tên camera*",self.name),("Mã vị trí*",self.position),("RTSP URL*",self.url),("Loại khu vực*",self.zone_type),("Sức chứa",self.capacity),("FPS AI",self.fps),("FPS preview",self.preview_fps),("",self.preview_warning),("Confidence",self.conf),("Detector image size",self.imgsz),("Ngưỡng giao polygon",self.overlap),("",self.roi),("",self.debug_overlay),("Xác nhận đỗ (giây)",self.park),("Xác nhận rời (giây)",self.exit),("Giữ track mất (giây)",self.grace),("Grace mất detection (giây)",self.miss_grace),("Xoay hình",self.rotation),("",self.enabled)]: form.addRow(label,w)
        buttons=QDialogButtonBox(QDialogButtonBox.Save|QDialogButtonBox.Cancel); buttons.accepted.connect(self.accept); buttons.rejected.connect(self.reject); form.addRow(buttons)
        self.fps.setValue(settings.processing_fps); self.preview_fps.setValue(5); self.capacity.setValue(1); self.conf.setValue(.20); self.imgsz.setCurrentIndex(self.imgsz.findData(settings.detector_image_size)); self.overlap.setValue(.20); self.roi.setChecked(True); self.debug_overlay.setChecked(settings.ai_debug_overlay); self.park.setValue(5); self.exit.setValue(2); self.grace.setValue(3); self.miss_grace.setValue(5); self.enabled.setChecked(True)
        if camera:
            self.code.setText(camera.camera_code); self.name.setText(camera.camera_name); self.position.setText(camera.parking_position_code); self.url.setText(camera.rtsp_url); self.zone_type.setCurrentIndex(max(0,self.zone_type.findData(camera.zone_type))); self.capacity.setValue(camera.capacity); self.fps.setValue(camera.processing_fps); self.preview_fps.setValue(int(camera.preview_fps)); self.conf.setValue(camera.vehicle_confidence); self.imgsz.setCurrentIndex(max(0,self.imgsz.findData(camera.detector_image_size))); self.overlap.setValue(camera.vehicle_polygon_overlap_threshold); self.roi.setChecked(camera.use_polygon_roi); self.debug_overlay.setChecked(camera.ai_debug_overlay); self.park.setValue(int(camera.parking_confirm_seconds)); self.exit.setValue(int(camera.exit_confirm_seconds)); self.grace.setValue(int(camera.track_lost_grace_seconds)); self.miss_grace.setValue(int(camera.detection_miss_grace_seconds)); self.rotation.setCurrentIndex(max(0,self.rotation.findData(camera.rotation_degrees))); self.enabled.setChecked(camera.enabled)

    def accept(self):
        if not all(x.text().strip() for x in (self.code,self.name,self.position,self.url)): QMessageBox.warning(self,"Thiếu dữ liệu","Vui lòng nhập đủ các trường bắt buộc."); return
        if self.enabled.isChecked() and self.zone_type.currentData()=="LEGACY_UNSET": QMessageBox.warning(self,"Chưa cấu hình","Phải chọn loại khu vực trước khi bật camera."); return
        super().accept()

    def values(self):
        zone_type=str(self.zone_type.currentData())
        return dict(camera_code=self.code.text().strip(),camera_name=self.name.text().strip(),parking_position_code=self.position.text().strip(),rtsp_url=self.url.text().strip(),zone_type=zone_type,capacity=self.capacity.value(),enabled=self.enabled.isChecked(),processing_fps=self.fps.value(),preview_fps=self.preview_fps.value(),vehicle_confidence=self.conf.value(),enable_motorcycles=zone_type=="MOTORCYCLE_ZONE",detector_image_size=int(self.imgsz.currentData()),use_polygon_roi=self.roi.isChecked(),vehicle_polygon_overlap_threshold=self.overlap.value(),ai_debug_overlay=self.debug_overlay.isChecked(),parking_confirm_seconds=self.park.value(),exit_confirm_seconds=self.exit.value(),track_lost_grace_seconds=self.grace.value(),detection_miss_grace_seconds=self.miss_grace.value(),rotation_degrees=int(self.rotation.currentData()))
